modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/ssblur/scriptor/issues"
license = "CC0-1.0"

[[mods]]
modId = "scriptor"
version = "${version}"
displayName = "Scriptor Magicae"
authors = "SSBlur"
description = '''
Knowledge is power!
'''
logoFile = "icon.png"

[[dependencies.scriptor]]
modId = "neoforge"
type = "required"
versionRange = "[20.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scriptor]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scriptor]]
modId = "unfocused"
type = "required"
versionRange = "[${unfocused_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "scriptor.mixins.json"
